# Generated by Django 3.1.3 on 2022-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220707_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=10),
        ),
    ]
